### PR TITLE
Add indentations for busuanzi_count settings to keep consistent with others

### PR DESCRIPTION
**Pull request by Maples7**

### CODE REVIEW

**Comment by ivan-nginx** [comment]
https://github.com/theme-next/hexo-theme-next/blob/7a7681f188080b52a3a96817e9d95641f718589c/_config.yml#L698-L707

**Comment by Maples7** [comment]
I am confused why these settings(site_uv, page_uv...) are here too, but I found they are truly in source code.
And adding `busuanzi_count` to show they are not the top level.

**Comment by ivan-nginx** [comment]
> I am confused why these settings(site_uv, page_uv...) are here too, but I found they are truly in source code.

This can't be in source now. Here is pull with new settings: https://github.com/theme-next/hexo-theme-next/pull/129

**Comment by Maples7** [comment]
But it really exists: https://github.com/theme-next/hexo-theme-next/blob/master/source/css/_common/components/third-party/busuanzi-counter.styl#L21. The same for the other fields while you can search them.

Maybe we should fix it in the source code again and replace those field names in docs.

**Comment by ivan-nginx** [comment]
This is style file, and seems to be bug, need to fix this.
Anyway, new configuration already in use. Old config not working, so, need to rewrite docs.

**Pull request closed without merging**
