### PR TITLE
Update markdown links

### PR DESCRIPTION
**Pull request by 1v9**
* related #20

### CODE REVIEW

**Comment by 1v9** [comment]
Oh no


What's wrong? render?

**Comment by 1v9** [comment]
I understand, is anyone interested, remove `<p>` ?
```html
<p>[Hexo](https://hexo.io) is a fast and powerful...
```

**Comment by 1v9** [comment]
I found some markdown links won't render, I will check them.

**Comment by ivan-nginx** [comment]
Yeah, that's right! :+1:

**Pull request merged**
