### PR TITLE
Update Docs

### PR DESCRIPTION
**Pull request by stevenjoezhang**

### CODE REVIEW

**Review by 1v9 — APPROVED** [review]

**Review by ivan-nginx — COMMENTED** [review]
Please, preserve 2-spaces indents between global sections in `_config.yml`.

**Comment by stevenjoezhang** [comment]
Seems in some sections, the indent is just 1 line before this commit:
https://github.com/theme-next/theme-next.org/blob/e4f13d1c1953f0ee4036c3da2afc8048a8ba6e85/_config.yml

**Comment by ivan-nginx** [comment]
Yeah, there is. Anyway, need 2-indents for separate sections and better visioning.

**Comment by stevenjoezhang** [comment]
Sure, I'll fix it in the next PR

**Pull request merged**
