### PR TITLE
Fix gitlab pages update time

### PR DESCRIPTION
**Pull request by jiangtj**
Thank sli1989 and wafer-li https://github.com/theme-next/theme-next.org/pull/2#issuecomment-446875473
Sorry, I don't add this commands. It's effective at update time.
```
"git ls-files -z | while read -d '' path; do touch -d \"$(git log -1 --format=\"@%ct\" \"$path\")\" \"$path\"; done"
```
I also test this commands, but nothing happened. Is it need?
```
export TZ='Asia/Shanghai'
```
@sli1989 Is there any other suggestion?

### CODE REVIEW

**Comment by sli1989** [comment]
Maybe to make this works, all my origin commands are needed as I know.
in your [pr](https://github.com/theme-next/theme-next.org/pull/2/files#diff-6670e78b93312d202f6c408df2ab1e98R138), the `.gitlab-ci.yml` Configuration is repeated.

image

U need test and verify all of this and smooth the text. 😢 

---

and the section of Restore last modified time in HTTPS way may need be deleted since `DEPLOY_PRIVATE_KEY` is related to SHH way, i don't know yet.

**Comment by jiangtj** [comment]
@sli1989 Okay, I will test it and smooth the text later.
My English is poor, so I don't smooth at first....
If there are any word errors, hope you can point out them.

**Comment by jiangtj** [comment]
@sli1989 Updated. Live demo in here <https://jiangtj.gitlab.io/next-test/gemini/docs/getting-started/deployment/>

**Comment by ivan-nginx** [comment]
@JiangTJ Note: for around spaces in tabs or another blocks inside blocks, need to replace default render:

https://github.com/theme-next/theme-next.org/blob/9fc72e94decff11d0fb802d830735f98e489729a/hexo-theme-next-autoinstall.sh#L68-L72

**Comment by jiangtj** [comment]
@ivan-nginx Fixed test site :laughing:

**Comment by ivan-nginx** [comment]
So, merge it? :+1: 

P.S. Need to set up auto-deploy after merge pull here.

**Pull request merged**
